version: '3.7'
services:
  api:
    image: unqdifi/covid-back-node:v2
    restart: unless-stopped
    ports:
      - '9001:9001'
      - '9991:9991'
    environment:
      NODE_ENV: production
      LOG_LEVEL: error
      SERVER_PORT: 9001
      ACCESS_TOKEN_SECRET: 12345
      DATABASE_URL: "postgres://covid:54321@db:5432/covid"
    volumes:
      - ./logs/:/opt/app/logs/
    depends_on:
      - db
      - recreate

  recreate:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "/opt/app/recreate-db.sh"]
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgres://covid:54321@db:5432/covid"
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: covid
      POSTGRES_PASSWORD: "54321"
    restart: unless-stopped
    volumes:
      - ./db/data:/var/lib/postgresql/data
  
  prometheus:
    image: prom/prometheus:v2.19.1
    ports:
      - '9090:9090/tcp'
    volumes:
      - prometheus-data:/prometheus/
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:7.0.3
    ports:
      - '3000:3000/tcp'
    volumes:
      - grafana-data:/var/lib/grafana
  
  node-exporter:
    image: prom/node-exporter
    ports:
      - '9100:9100'

volumes:
  prometheus-data:
  grafana-data:
